/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;


import Datos.CPagos;
import Logica.LPagos;
import com.mysql.jdbc.StringUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Esteban
 */
public class frmPagos extends javax.swing.JFrame {

    /**
     * Creates new form frmPagos
     */
    public frmPagos() {
        initComponents();
    }
    
    private String accion = "";
    
    void ocultar_colummas(){
        TPagosHisto.getColumnModel().getColumn(0).setMaxWidth(0);
         TPagosHisto.getColumnModel().getColumn(0).setMinWidth(0);
          TPagosHisto.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    void inhabilitar(){
        TNProveedor.setEnabled(false);
        CTipo.setEnabled(false);
        TTotal.setEditable(false);
        TNComprobante.setEnabled(false);
    }
    void limpiarcampos(){
        TNProveedor.setText("");
        CTipo.setSelectedIndex(0);
        TTotal.setText("");
        TNComprobante.setText("");
        TDescripcion.setText("");
        
    }
      void habilitar(){
        TNProveedor.setEnabled(true);
        CTipo.setEnabled(true);
        TTotal.setEditable(true);
        TNComprobante.setEnabled(true);
    }
      
    void mostrar (String buscar){
        try {
            DefaultTableModel modelo;
            LPagos func= new LPagos();
            modelo = func.mostrar(buscar);
          
            TPagosHisto.setModel(modelo);
            //ocultar_colummas();
            LTotalRegistros.setText("Total Reg "+Integer.toString(func.totalregistros));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null,e);
        }
    }
    
    void mensaje(String mens){
       JOptionPane.showMessageDialog(rootPane,mens); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TPagosHisto = new javax.swing.JTable();
        CTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TTotal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TDescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        TNComprobante = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        BtnGuardar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnConfirmar = new javax.swing.JButton();
        LTotalRegistros = new javax.swing.JLabel();
        Panel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TRazonSocial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TNProveedor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        TFecha = new com.toedter.calendar.JDateChooser();
        LAccion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TPagosHisto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TPagosHisto.setToolTipText("Historico de pagos");
        TPagosHisto.setName(""); // NOI18N
        jScrollPane1.setViewportView(TPagosHisto);

        CTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EFECTIVO", "TRANSF", "CHEQUE" }));

        jLabel2.setText("Tipo");

        jLabel3.setText("Total");

        TTotal.setText("0.00");
        TTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TTotalKeyTyped(evt);
            }
        });

        jLabel4.setText("Descripcion");

        TDescripcion.setColumns(20);
        TDescripcion.setRows(5);
        jScrollPane2.setViewportView(TDescripcion);

        jLabel5.setText("N Comprobante");

        jLabel6.setText("Fecha");

        BtnGuardar.setText("AGREGAR");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnConfirmar.setText("CONFIRMAR");
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        LTotalRegistros.setText("jLabel7");

        Panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null), "Datos Proveedor"));

        jLabel7.setText("N Proveedor");

        TRazonSocial.setEditable(false);
        TRazonSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRazonSocialActionPerformed(evt);
            }
        });

        jLabel8.setText("Razon Social");

        TNProveedor.setEditable(false);
        TNProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNProveedorActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar Porveedor");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel1Layout = new javax.swing.GroupLayout(Panel1);
        Panel1.setLayout(Panel1Layout);
        Panel1Layout.setHorizontalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TNProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TRazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        Panel1Layout.setVerticalGroup(
            Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TNProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addGroup(Panel1Layout.createSequentialGroup()
                        .addGroup(Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TRazonSocial)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        TFecha.setDateFormatString("yyyy/MM/dd");

        LAccion.setText("Formulario en modo: ");

        jLabel1.setBackground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Historico de pagos del proveedor seleccionado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnGuardar)
                                .addGap(32, 32, 32)
                                .addComponent(btnModificar)
                                .addGap(42, 42, 42)
                                .addComponent(btnConfirmar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(TNComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LAccion)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LTotalRegistros))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(264, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LTotalRegistros)
                .addGap(18, 18, 18)
                .addComponent(LAccion)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(CTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(TNComprobante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardar)
                    .addComponent(btnModificar)
                    .addComponent(btnConfirmar))
                .addGap(145, 145, 145))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
        habilitar();
        accion="guardar";
        LAccion.setText("Formulario en modo: "+accion);
        limpiarcampos();
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        // TODO add your handling code here:
        
        if(TTotal.getText().length()==0){
            this.mensaje("debes ingresar un total");
            TTotal.requestFocus();
            return ;
        }
        
        int aux =0;
        try {
            Integer.parseInt(TNProveedor.getText());
        } catch (Exception e) {
            this.mensaje("debes tener un numero de proveedor");
            return ;
        }
        
        
        
        CPagos dts = new CPagos();
        
        LPagos func = new LPagos();
        //mensaje("por ingresar 1");
        dts.setIdProveedor(Integer.parseInt(TNProveedor.getText()));
        dts.setIdresponsable(10);
        dts.setTotal(Double.parseDouble(TTotal.getText()));
        dts.setTipo(CTipo.getSelectedItem().toString());
        dts.setUnico("--");
        dts.setDescripcion(TDescripcion.getText());
        dts.setNTransaccion(TNComprobante.getText());
        
        
            try {
        //jDateChooser el nombre la variable  del componente jdatecgooser
         Date  fecha=TFecha.getDate();
        DateFormat f=new SimpleDateFormat("yyyy-MM-dd");
        String fecha2=f.format(fecha); 
        //textFecha nombre de la variable del componenten jtextfiel
        //TNComprobante.setText(fecha2);
        //mensaje(fecha2);
        
        dts.setFecha(fecha2);
       
    } catch (NullPointerException  e) {
                mensaje("Fecha Incorrecta ");
                return;
    }
        if(accion.equals("guardar")){
            if(func.insertar(dts)){
                mensaje("Se guardo el pago");
                mostrar(TNProveedor.getText());
                limpiarcampos();
                LAccion.setText("Formulario en modo: ");
                accion="";
            }
        }else{
            if(accion.equals("modificar")){
                mensaje("NO Tiene Permiso \n para modificar");
            }else{
                mensaje("NO Selecciono opcion");
            }
        }
        
        
       
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void TTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TTotalKeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();
        //TNComprobante.setText(String.valueOf(car));
        if(!( (car>='0') && (car<='9') ) && (car!='.')  )
            evt.consume();
    }//GEN-LAST:event_TTotalKeyTyped

    private void TRazonSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRazonSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRazonSocialActionPerformed

    private void TNProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNProveedorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frmModalBuscaProv BusProv = new frmModalBuscaProv(this,true);
        BusProv.setVisible(true);
        TNProveedor.setText(BusProv.getValor1());
        TRazonSocial.setText(BusProv.getValor2());
        if(TRazonSocial.getText().length()!=0){
            mostrar(TNProveedor.getText());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        accion="modificar";
        LAccion.setText("Formulario en modo: "+accion);
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPagos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPagos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JComboBox<String> CTipo;
    private javax.swing.JLabel LAccion;
    private javax.swing.JLabel LTotalRegistros;
    private javax.swing.JPanel Panel1;
    private javax.swing.JTextArea TDescripcion;
    private com.toedter.calendar.JDateChooser TFecha;
    private javax.swing.JTextField TNComprobante;
    private javax.swing.JTextField TNProveedor;
    private javax.swing.JTable TPagosHisto;
    private javax.swing.JTextField TRazonSocial;
    private javax.swing.JTextField TTotal;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
